version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    rebase-strategy: "disabled"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 99
